# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:18
from __future__ import unicode_literals

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headland_app', '0004_auto_20160527_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(default='/static/headland/img/default.png', upload_to='avatars'),
        ),
    ]
