# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:32
from __future__ import unicode_literals

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headland_app', '0005_auto_20160527_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(null=True, upload_to='avatars'),
        ),
    ]
